<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <UseWPF>true</UseWPF>
    <AssemblyName>BrowserShell.WebView.Wpf</AssemblyName>
    <RootNamespace>BrowserShell.WebView.Wpf</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.Web.WebView2" />
    <PackageReference Include="Serilog.Extensions.Hosting" />
    <PackageReference Include="Serilog.Formatting.Compact" />
    <PackageReference Include="Serilog.Sinks.Console" />
    <PackageReference Include="Serilog.Sinks.File" />
    <ProjectReference Include="..\BrowserShell.Service.SDK\BrowserShell.Service.SDK.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Assets\BrowserShell.ico" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="BrowserShell.WebView.Wpf.Tests" />
  </ItemGroup>
</Project>
